Отрисуй меня полностью (часть 1)
htmlacademy-javascript/1987675-keksobooking-25 pull request #5
Opened 2022-03-10 20:35 UTC by Linner-Kot

2022-03-11 05:16 UTC, Dima-Dim requested changes

2022-03-11 05:16 UTC, Dima-Dim commented on js/data.js
> +  palace: 'Дворец',
https://up.htmlacademy.ru/javascript/25/criteries#b8
Первые буквы должны быть заглавными.

2022-03-11 05:16 UTC, Dima-Dim commented on js/data.js
> +const PROPERTY_TYPES = Object.keys(OFFER_TYPES);
`PROPERTY_TYPES` - вычисляется, по этому это не константа.

2022-03-11 05:16 UTC, Dima-Dim commented on js/data.js
> +const LATITUDE_MIN = 35.65000;
Тут можно использовать перечисление, потому что это связанные по смыслу константы.

2022-03-11 05:16 UTC, Dima-Dim commented on js/markup-generate.js
> +similarOffers.forEach((offer) => {
Такие конструкции лучше оборачивать в функции, для большей гибкости их использования.

2022-03-11 13:05 UTC, Linner-Kot commented on js/data.js
> +  palace: 'Дворец',
"...допускается использование объектов в качестве словарей..."
Так можно?

2022-03-12 05:33 UTC, Dima-Dim commented on js/data.js
> +  palace: 'Дворец',
Хорошо. Но если на защите будут придираться, нужно будет поправить.

2022-03-12 05:34 UTC, merged